stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - docker-compose build

test-job:
  stage: test
  script:
    - docker-compose run app sh -c "python manage.py test"

cleanup-job:
  stage: cleanup
  script:
    - docker rmi -f notify-app

deploy-job:
  stage: deploy
  script:
    - docker-compose up -d
