stages:
  - build
  - test
  - cleanup
  - deploy

build-job:
  stage: build
  script:
    - docker-compose build

test-job:
  stage: test
  script:
    - docker-compose up -d
    - docker-compose exec app bash -c "python manage.py test"
    - docker-compose down

cleanup-job:
  stage: cleanup
  script:
    - docker rmi -f notify-app

deploy-job:
  stage: deploy
  script:
    - docker-compose up -d
