version: '3'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: fabrique
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fabrique123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate --noinput
      && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq

  celery:
    build: .
    command: celery -A notify worker -B -l INFO
    depends_on:
      - db
      - rabbitmq
    restart: unless-stopped

volumes:
  postgres-data:
